site_name: Graph Algorithms
site_description: 'A course on graph algorithms. All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/graph-algorithms'
repo_url: 'https://github.com/dmccreary/graph-algorithms'

nav:
  - Home: index.md
  - About: about.md
  - Topics: topic-lists.md
  - List of Graph Algorithms: list-of-algorithms.md
  - Lessons:
    - Introduction: lessons/index.md
    - Terminology: lessons/01-graph-terminology.md
    - Labeled Property Graphs: lpg.md
    - Graph Query Languages: graph-query-languages.md
    - Relationship Traversal: relationship-traversal.md
  - Generating Graph Data:
    - Introduction: data/index.md
    - US Cities: data/us-cities/index.md
  - Sims:
    - Introduction: sims/index.md
    - Degree: sims/degree/index.md
    - Weighted: sims/weighted/index.md
    - Force Directed Graph Layout: sims/force/index.md
    - Breath First Search: sims/bfs/index.md
    - Shortest Path: sims/shortest-path/index.md
    - PageRank: sims/page-rank/index.md
    - Matching: sims/matching/index.md
    - Data Element Matching: sims/data-element-match/index.md
  - How We Built This Site: how-we-built-this-site.md





  - Glossary: glossary.md
  - License: license.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  extra_css:
    - styles/custom.css
  # logo: img/my-icon.png
  # favicon: img/my-icon.png
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX